[F-25]: update meteor desktop
sharekey/meteor-desktop pull request #66
Opened 2022-08-15 10:49 UTC by marozartsem9

https://yt.sharekey.com/agiles/110-34/current?issue=F-25

What was done:
- merged branch with electron-update from (https://github.com/Meteor-Community-Packages/meteor-desktop/pull/8)
- fix issue with single instance: syntax was changed in the newer version of electron.

2022-08-15 11:03 UTC, Strangerxxx requested changes
as we have meteor-desktop hard forked we should have different namespace for meteor packages - skadmin

2022-08-15 11:03 UTC, Strangerxxx commented on plugins/bundler/package.js
> +    name: 'communitypackages:meteor-desktop-bundler',
this package must be under skadmin namespace

2022-08-15 11:03 UTC, Strangerxxx commented on plugins/watcher/package.js
> +    name: 'communitypackages:meteor-desktop-watcher',
this package must be under skadmin namespace

2022-08-15 11:03 UTC, Strangerxxx commented on plugins/watcher/package.js
> +        'communitypackages:meteor-desktop-bundler@3.0.0',
this package must be under skadmin namespace

2022-08-15 11:03 UTC, Strangerxxx commented on plugins/watcher/watcher.js
> +} else if ('communitypackages:meteor-desktop-bundler' in Package) {
this package must be under skadmin namespace

2022-08-15 11:03 UTC, Strangerxxx commented on plugins/watcher/watcher.js
> +            Package['communitypackages:meteor-desktop-bundler'].METEOR_DESKTOP_VERSION.version : null;
this package must be under skadmin namespace

2022-08-15 11:03 UTC, Strangerxxx commented on plugins/watcher/watcher.js
> +                'have communitypackages:meteor-desktop-bundler package added to your project?');
this package must be under skadmin namespace

2022-08-15 11:03 UTC, Strangerxxx commented on plugins/watcher/watcher.js
> +        'communitypackages:meteor-desktop-bundler package added to your project?');
this package must be under skadmin namespace

2022-08-15 11:03 UTC, Strangerxxx commented on tests/unit/meteorManager.test.js
> +                    'communitypackages:meteor-desktop-watcher@0.0.11'
this package must be under skadmin namespace

2022-08-16 10:13 UTC, Strangerxxx approved these changes
lgtm

2022-08-17 08:49 UTC, merged

2022-08-29 08:38 UTC, StorytellerCZ commented
@marozartsem9 would you be willing to push your fixes upstream?

2022-08-29 09:43 UTC, marozartsem9 commented
> @marozartsem9 would you be willing to push your fixes upstream?

@StorytellerCZ , Hi!
https://github.com/Meteor-Community-Packages/meteor-desktop/pull/10